### ISSUE TITLE
Visualisations: Wrap Code in Functions

### ISSUE THREAD

**Issue by printerscanner** [overbrowsing/pruner#1]
**Description:**
We should encapsulate the visualisation plotting code inside functions to improve structure and readability. This will make it more modular and easier to maintain. A suggested format is:

```
def plot_graph():
    # All the plotting code here

if __name__ == '__main__':
    plot_graph()

```
[Link to code](https://github.com/overbrowsing/pruner/blob/main/visualisation/app.py)

**Comment by headlesshorse** [comment]
I agree—we should encapsulate the visualisation plotting code in functions to improve structure, readability, and maintainability.
