### ISSUE TITLE
Accept Images as Input and Export Optimized Tiled Versions

### ISSUE THREAD

**Issue by printerscanner** [overbrowsing/pruner#4]
**Description:**
The project should be enhanced to accept whole images as input and export optimized, tiled versions of the images. This will expand the functionality and make the tool more useful by generating both tiled images at appropriate sizes and visualizations.

**Comment by headlesshorse** [comment]
I think I had already jumped to idea in another issue!

"I agree, and we could potentially create an interface as an HTML document where the graph is visualised and the files (tiles) are generated, making the tool even more interactive and user-friendly."

Would need to consider if this app also compresses, strip out metadata of images and exports to a modern file type (WebP).

**Comment by headlesshorse** [comment]
Tile Calculator and Tile Maker were just added yesterday to automate the process of making tiles. It imports images and exports them processed along with the HTML snippet making installation simple.
